# Specify which distribution to on.
dist: xenial

# Tell Travis CI which language to use.
language: node_js

# Tell Travis CI which notifications to send.
notifications:
  email:
    on_success: never
    on_failure: change

# Whitelist branches for the "push" build check.
branches:
  only:
    - master
    - /^dev\-release\/.*$/
    - /^feature\/.*$/
    - /^fix\/.*$/

node_js:
  - "node"
  - "11"
  - "10"
  - "8"

before_install:
  - npm install -g grunt-cli

before_script:
  # Create and stage a test file.
  - grunt --version > test.txt && git add test.txt

script:
  # Perform linting
  - grunt jshint
  # Perform testing
  - grunt test

after_script:
  # Clean up test files.
  - git reset HEAD test.txt && rm -f test.txt

jobs:
  include:
    - stage: deploy
      name: "NPM Deployment"
      node_js: "node"
      before_install: skip
      before_script: skip
      script: skip
      after_script: skip
      deploy:
        provider: npm
        edge: true
        email: "$NPM_EMAIL"
        api_key: "$NPM_API_KEY"
        on:
          branch: master
    - stage: release
      name: "GitHub Release"
      node_js: "node"
      before_install: skip
      before_script: skip
      script: skip
      after_script: skip
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "Tim Nolte"
        - git config --local user.email "$GITHUB_USER_EMAIL"
        - export GIT_TAG_VERSION=$(npm view ./ version)
        - git tag "v$GIT_TAG_VERSION"
      deploy:
        provider: releases
        edge: true
        api_key: "$GITHUB_OAUTH_TOKEN"
        skip_cleanup: true
        on:
          condition: -z $(git tag --points-at $TRAVIS_COMMIT)
          branch: master
